import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import { normalizeLocalizedCopy } from "../utils/localization";

const STORAGE_KEY = "cw-language";

const LANGUAGE_OPTIONS = normalizeLocalizedCopy([
  { value: "english", short: "EN", label: "English" },
  { value: "hindi", short: "à¤¹à¤¿à¤‚", label: "à¤¹à¤¿à¤¨à¥à¤¦à¥€" },
  { value: "hinglish", short: "HING", label: "Hinglish" },
]);

const TRANSLATIONS = normalizeLocalizedCopy({
  english: {
    switcherLabel: "App language",
    navFeatures: "Features",
    navHow: "How it works",
    navCrops: "Crops",
    navOpenApp: "Open app",
    heroEyebrow: "AI | ML | Agriculture",
    heroGrow: "Grow",
    heroSmarter: "smarter",
    heroField: "for the field",
    heroSub: "Predict the best crops and fertilizers from soil conditions, real-time weather, and an ensemble of machine learning models.",
    heroCropBtn: "Crop Recommendation",
    heroFertilizerBtn: "Fertilizer Recommendation",
    statsCropTypes: "Crop Types",
    statsFertilizers: "Fertilizers",
    statsModels: "ML Models",
    statsAccuracy: "Accuracy",
    featuresLabel: "Core Features",
    featuresTitleA: "Practical guidance,",
    featuresTitleB: "built for decisions",
    processLabel: "The Process",
    processTitleA: "Three steps to",
    processTitleB: "better crop choices",
    cropsLabel: "Supported Crops",
    cropsTitleA: "22 crops,",
    cropsTitleB: "one engine",
    ctaLabel: "Get Started",
    ctaTitleA: "Start with your field.",
    ctaTitleB: "Get a recommendation you can use.",
    ctaSub: "Use soil inputs, local weather, and AI guidance to compare options before you commit to a crop or fertilizer plan.",
    ctaCropBtn: "Start with crops >",
    ctaFertilizerBtn: "Try fertilizers >",
    badgeMl: "ML-Powered",
    badgeWeather: "Real-time Weather",
    badgeSignup: "No signup needed",
    badgeFree: "Free to use",
    footerBuiltWith: "Built with ML + Gemini AI",
    footerCrops: "Crops",
    footerFertilizer: "Fertilizer",
    cropTitle: "Crop Recommender",
    cropSubtitle: "Two engines | One goal: the right crop for your land",
    cropHistory: "Prediction History",
    cropTabMl: "ML Model",
    cropTabMlDesc: "N | P | K | Climate data",
    cropTabAi: "AI Advisor",
    cropTabAiDesc: "Region | Season | Gemini",
    fertilizerTitle: "Fertilizer Recommender",
    fertilizerSubtitle: "Enter soil and crop data for an AI-powered fertilizer suggestion",
    fertilizerExample: "Load example",
    fertilizerHistory: "History",
    historyEyebrow: "Saved Decisions",
    historyTitle: "Prediction History",
    historySubtitle: "Track recent crop and fertilizer recommendations in one place.",
    historyHome: "Home",
    historyBack: "Back",
    historyAll: "All",
    historyCrop: "Crop",
    historyFertilizer: "Fertilizer",
    historyClear: "Clear History",
    historyTotalSaved: "Total Saved",
    historyCropPredictions: "Crop Predictions",
    historyFertilizerPredictions: "Fertilizer Predictions",
    historyAverageConfidence: "Average Confidence",
    historyMostPredictedCrops: "Most Predicted Crops",
    historyNoCropPredictions: "No crop predictions yet",
    historyMostRecommendedFertilizers: "Most Recommended Fertilizers",
    historyNoFertilizerPredictions: "No fertilizer predictions yet",
    historyLatestActivity: "Latest Activity",
    historyType: "Type",
    historyResult: "Result",
    historySaved: "Saved",
    historyNoActivity: "No activity yet",
    historyNoSavedPredictions: "No saved predictions yet",
    historyEmptyCopy: "Run a crop or fertilizer prediction and it will show up here automatically.",
    historyCropPredictionLabel: "Crop Prediction",
    historyFertilizerPredictionLabel: "Fertilizer Prediction",
    historyPredictionSaved: "Prediction saved",
    historyConfidenceLabel: "Confidence",
    historyUnknownTime: "Unknown time",
  },
  hindi: {
    switcherLabel: "à¤à¤ª à¤•à¥€ à¤­à¤¾à¤·à¤¾",
    navFeatures: "à¤µà¤¿à¤¶à¥‡à¤·à¤¤à¤¾à¤à¤",
    navHow: "à¤•à¥ˆà¤¸à¥‡ à¤•à¤¾à¤® à¤•à¤°à¤¤à¤¾ à¤¹à¥ˆ",
    navCrops: "à¤«à¤¸à¤²à¥‡à¤‚",
    navOpenApp: "à¤à¤ª à¤–à¥‹à¤²à¥‡à¤‚",
    heroEyebrow: "AI | ML | à¤•à¥ƒà¤·à¤¿",
    heroGrow: "à¤–à¥‡à¤¤à¥€",
    heroSmarter: "à¤”à¤° à¤¸à¤®à¤à¤¦à¤¾à¤°à¥€ à¤¸à¥‡",
    heroField: "à¤…à¤ªà¤¨à¥‡ à¤–à¥‡à¤¤ à¤•à¥‡ à¤²à¤¿à¤",
    heroSub: "à¤®à¤¿à¤Ÿà¥à¤Ÿà¥€ à¤•à¥€ à¤¸à¥à¤¥à¤¿à¤¤à¤¿, à¤°à¥€à¤¯à¤²-à¤Ÿà¤¾à¤‡à¤® à¤®à¥Œà¤¸à¤® à¤”à¤° à¤®à¤¶à¥€à¤¨ à¤²à¤°à¥à¤¨à¤¿à¤‚à¤— à¤®à¥‰à¤¡à¤²à¥à¤¸ à¤•à¥‡ à¤†à¤§à¤¾à¤° à¤ªà¤° à¤¬à¥‡à¤¹à¤¤à¤° à¤«à¤¸à¤² à¤”à¤° à¤‰à¤°à¥à¤µà¤°à¤• à¤šà¥à¤¨à¥‡à¤‚à¥¤",
    heroCropBtn: "à¤«à¤¸à¤² à¤¸à¥à¤à¤¾à¤µ",
    heroFertilizerBtn: "à¤‰à¤°à¥à¤µà¤°à¤• à¤¸à¥à¤à¤¾à¤µ",
    statsCropTypes: "à¤«à¤¸à¤² à¤ªà¥à¤°à¤•à¤¾à¤°",
    statsFertilizers: "à¤‰à¤°à¥à¤µà¤°à¤•",
    statsModels: "ML à¤®à¥‰à¤¡à¤²",
    statsAccuracy: "à¤¸à¤Ÿà¥€à¤•à¤¤à¤¾",
    featuresLabel: "à¤®à¥à¤–à¥à¤¯ à¤µà¤¿à¤¶à¥‡à¤·à¤¤à¤¾à¤à¤",
    featuresTitleA: "à¤µà¥à¤¯à¤¾à¤µà¤¹à¤¾à¤°à¤¿à¤• à¤¸à¤²à¤¾à¤¹,",
    featuresTitleB: "à¤¸à¤¹à¥€ à¤«à¥ˆà¤¸à¤²à¥‹à¤‚ à¤•à¥‡ à¤²à¤¿à¤",
    processLabel: "à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾",
    processTitleA: "à¤¬à¥‡à¤¹à¤¤à¤° à¤«à¤¸à¤² à¤šà¥à¤¨à¤¨à¥‡ à¤•à¥‡",
    processTitleB: "à¤¤à¥€à¤¨ à¤†à¤¸à¤¾à¤¨ à¤šà¤°à¤£",
    cropsLabel: "à¤¸à¤®à¤°à¥à¤¥à¤¿à¤¤ à¤«à¤¸à¤²à¥‡à¤‚",
    cropsTitleA: "22 à¤«à¤¸à¤²à¥‡à¤‚,",
    cropsTitleB: "à¤à¤• à¤‡à¤‚à¤œà¤¨",
    ctaLabel: "à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚",
    ctaTitleA: "à¤…à¤ªà¤¨à¥‡ à¤–à¥‡à¤¤ à¤¸à¥‡ à¤¶à¥à¤°à¥à¤†à¤¤ à¤•à¤°à¥‡à¤‚à¥¤",
    ctaTitleB: "à¤•à¤¾à¤® à¤•à¥€ à¤¸à¤²à¤¾à¤¹ à¤¤à¥à¤°à¤‚à¤¤ à¤ªà¤¾à¤à¤à¥¤",
    ctaSub: "à¤®à¤¿à¤Ÿà¥à¤Ÿà¥€, à¤¸à¥à¤¥à¤¾à¤¨à¥€à¤¯ à¤®à¥Œà¤¸à¤® à¤”à¤° AI à¤®à¤¾à¤°à¥à¤—à¤¦à¤°à¥à¤¶à¤¨ à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¤•à¥‡ à¤«à¤¸à¤² à¤¯à¤¾ à¤‰à¤°à¥à¤µà¤°à¤• à¤¯à¥‹à¤œà¤¨à¤¾ à¤¤à¤¯ à¤•à¤°à¤¨à¥‡ à¤¸à¥‡ à¤ªà¤¹à¤²à¥‡ à¤µà¤¿à¤•à¤²à¥à¤ªà¥‹à¤‚ à¤•à¥€ à¤¤à¥à¤²à¤¨à¤¾ à¤•à¤°à¥‡à¤‚à¥¤",
    ctaCropBtn: "à¤«à¤¸à¤² à¤¸à¥‡ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚ >",
    ctaFertilizerBtn: "à¤‰à¤°à¥à¤µà¤°à¤• à¤¦à¥‡à¤–à¥‡à¤‚ >",
    badgeMl: "ML à¤†à¤§à¤¾à¤°à¤¿à¤¤",
    badgeWeather: "à¤°à¥€à¤¯à¤²-à¤Ÿà¤¾à¤‡à¤® à¤®à¥Œà¤¸à¤®",
    badgeSignup: "à¤¸à¤¾à¤‡à¤¨à¤…à¤ª à¤¨à¤¹à¥€à¤‚",
    badgeFree: "à¤¨à¤¿à¤ƒà¤¶à¥à¤²à¥à¤•",
    footerBuiltWith: "ML + Gemini AI à¤¸à¥‡ à¤¨à¤¿à¤°à¥à¤®à¤¿à¤¤",
    footerCrops: "à¤«à¤¸à¤²à¥‡à¤‚",
    footerFertilizer: "à¤‰à¤°à¥à¤µà¤°à¤•",
    cropTitle: "à¤«à¤¸à¤² à¤¸à¥à¤à¤¾à¤µ",
    cropSubtitle: "à¤¦à¥‹ à¤‡à¤‚à¤œà¤¨ | à¤à¤• à¤²à¤•à¥à¤·à¥à¤¯: à¤†à¤ªà¤•à¥€ à¤œà¤®à¥€à¤¨ à¤•à¥‡ à¤²à¤¿à¤ à¤¸à¤¹à¥€ à¤«à¤¸à¤²",
    cropHistory: "à¤¸à¥à¤à¤¾à¤µ à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸",
    cropTabMl: "ML à¤®à¥‰à¤¡à¤²",
    cropTabMlDesc: "N | P | K | à¤œà¤²à¤µà¤¾à¤¯à¥ à¤¡à¥‡à¤Ÿà¤¾",
    cropTabAi: "AI à¤¸à¤²à¤¾à¤¹à¤•à¤¾à¤°",
    cropTabAiDesc: "à¤•à¥à¤·à¥‡à¤¤à¥à¤° | à¤®à¥Œà¤¸à¤® | Gemini",
    fertilizerTitle: "à¤‰à¤°à¥à¤µà¤°à¤• à¤¸à¥à¤à¤¾à¤µ",
    fertilizerSubtitle: "AI à¤†à¤§à¤¾à¤°à¤¿à¤¤ à¤‰à¤°à¥à¤µà¤°à¤• à¤¸à¥à¤à¤¾à¤µ à¤•à¥‡ à¤²à¤¿à¤ à¤®à¤¿à¤Ÿà¥à¤Ÿà¥€ à¤”à¤° à¤«à¤¸à¤² à¤•à¤¾ à¤¡à¥‡à¤Ÿà¤¾ à¤­à¤°à¥‡à¤‚",
    fertilizerExample: "à¤‰à¤¦à¤¾à¤¹à¤°à¤£ à¤­à¤°à¥‡à¤‚",
    fertilizerHistory: "à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸",
    historyEyebrow: "à¤¸à¤¹à¥‡à¤œà¥‡ à¤—à¤ à¤¨à¤¿à¤°à¥à¤£à¤¯",
    historyTitle: "à¤¸à¥à¤à¤¾à¤µ à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸",
    historySubtitle: "à¤¹à¤¾à¤² à¤•à¥€ à¤«à¤¸à¤² à¤”à¤° à¤‰à¤°à¥à¤µà¤°à¤• à¤¸à¤¿à¤«à¤¾à¤°à¤¿à¤¶à¥‡à¤‚ à¤à¤• à¤¹à¥€ à¤œà¤—à¤¹ à¤¦à¥‡à¤–à¥‡à¤‚à¥¤",
    historyHome: "à¤¹à¥‹à¤®",
    historyBack: "à¤µà¤¾à¤ªà¤¸",
    historyAll: "à¤¸à¤­à¥€",
    historyCrop: "à¤«à¤¸à¤²",
    historyFertilizer: "à¤‰à¤°à¥à¤µà¤°à¤•",
    historyClear: "à¤‡à¤¤à¤¿à¤¹à¤¾à¤¸ à¤¸à¤¾à¤« à¤•à¤°à¥‡à¤‚",
  },
  hinglish: {
    switcherLabel: "App language",
    navFeatures: "Features",
    navHow: "Kaise kaam karta hai",
    navCrops: "Crops",
    navOpenApp: "App kholo",
    heroEyebrow: "AI | ML | Agriculture",
    heroGrow: "Kheti",
    heroSmarter: "aur smarter",
    heroField: "aapke field ke liye",
    heroSub: "Soil conditions, real-time weather aur machine learning models ke basis par best crop aur fertilizer choose karo.",
    heroCropBtn: "Crop Recommendation",
    heroFertilizerBtn: "Fertilizer Recommendation",
    statsCropTypes: "Crop Types",
    statsFertilizers: "Fertilizers",
    statsModels: "ML Models",
    statsAccuracy: "Accuracy",
    featuresLabel: "Core Features",
    featuresTitleA: "Practical guidance,",
    featuresTitleB: "better decisions ke liye",
    processLabel: "Process",
    processTitleA: "Better crop choice ke",
    processTitleB: "3 simple steps",
    cropsLabel: "Supported Crops",
    cropsTitleA: "22 crops,",
    cropsTitleB: "one engine",
    ctaLabel: "Get Started",
    ctaTitleA: "Apne field se start karo.",
    ctaTitleB: "Kaam ki recommendation pao.",
    ctaSub: "Soil inputs, local weather aur AI guidance ka use karke crop ya fertilizer plan decide karne se pehle options compare karo.",
    ctaCropBtn: "Crops se start karo >",
    ctaFertilizerBtn: "Fertilizers try karo >",
    badgeMl: "ML-Powered",
    badgeWeather: "Real-time Weather",
    badgeSignup: "No signup",
    badgeFree: "Free to use",
    footerBuiltWith: "ML + Gemini AI ke saath built",
    footerCrops: "Crops",
    footerFertilizer: "Fertilizer",
    cropTitle: "Crop Recommender",
    cropSubtitle: "Do engines | ek goal: aapki zameen ke liye sahi crop",
    cropHistory: "Prediction History",
    cropTabMl: "ML Model",
    cropTabMlDesc: "N | P | K | Climate data",
    cropTabAi: "AI Advisor",
    cropTabAiDesc: "Region | Season | Gemini",
    fertilizerTitle: "Fertilizer Recommender",
    fertilizerSubtitle: "AI-powered fertilizer suggestion ke liye soil aur crop data bharo",
    fertilizerExample: "Example load karo",
    fertilizerHistory: "History",
    historyEyebrow: "Saved Decisions",
    historyTitle: "Prediction History",
    historySubtitle: "Recent crop aur fertilizer recommendations ek jagah dekho.",
    historyHome: "Home",
    historyBack: "Back",
    historyAll: "All",
    historyCrop: "Crop",
    historyFertilizer: "Fertilizer",
    historyClear: "History clear karo",
    historyTotalSaved: "Total Saved",
    historyCropPredictions: "Crop Predictions",
    historyFertilizerPredictions: "Fertilizer Predictions",
    historyAverageConfidence: "Average Confidence",
    historyMostPredictedCrops: "Most Predicted Crops",
    historyNoCropPredictions: "Abhi tak crop predictions nahi hain",
    historyMostRecommendedFertilizers: "Most Recommended Fertilizers",
    historyNoFertilizerPredictions: "Abhi tak fertilizer predictions nahi hain",
    historyLatestActivity: "Latest Activity",
    historyType: "Type",
    historyResult: "Result",
    historySaved: "Saved",
    historyNoActivity: "Abhi tak koi activity nahi hai",
    historyNoSavedPredictions: "Abhi tak koi saved prediction nahi hai",
    historyEmptyCopy: "Ek crop ya fertilizer prediction run karo, woh yahan automatically dikh jayega.",
    historyCropPredictionLabel: "Crop Prediction",
    historyFertilizerPredictionLabel: "Fertilizer Prediction",
    historyPredictionSaved: "Prediction saved",
    historyConfidenceLabel: "Confidence",
    historyUnknownTime: "Unknown time",
  },
});

const LanguageContext = createContext(null);

function getInitialLanguage() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved && TRANSLATIONS[saved]) return saved;
  } catch {}
  return "english";
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch {}
  }, [language]);

  const value = useMemo(() => {
    const dictionary = TRANSLATIONS[language] || TRANSLATIONS.english;
    return {
      language,
      setLanguage,
      options: LANGUAGE_OPTIONS,
      t: (key) => dictionary[key] ?? TRANSLATIONS.english[key] ?? key,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}


