import React, { useState } from "react";
import { useHistory } from "react-router-dom";
import { cropData } from "../Data";
import { weightedVote } from "../../config/cropRecommenderConfig";
import { normalizeLocalizedCopy } from "../../utils/localization";
import { useLanguage } from "../../context/LanguageContext";
import { getCropUi, getLocalizedSeasons } from "../../config/cropCopy";
import {
  ConfidenceBar,
  CropCalendar,
  CropDetailPanel,
  downloadTextReport,
  getConfidenceExplanation,
  getConsensusExplanation,
  getCropReasonHighlights,
  getDecisionEdgeExplanation,
  getSeasonWindowLabel,
  getSuitabilityMeta,
  getTopCropSuggestions,
  mapCropToFertilizerType,
  RadarChart,
  shareResult,
  VoteTriangle,
} from "./CropShared";

function CropMlResultPanel({ predictionData, formData, onBack }) {
  const history = useHistory();
  const { language } = useLanguage();
  const ui = normalizeLocalizedCopy(getCropUi(language));
  const [selectedCrop, setSelectedCrop] = useState(null);
  const [imgError, setImgError] = useState(false);

  const xgbConf = Math.min(100, Math.max(0, parseFloat(predictionData.xgb_model_probability)));
  const rfConf = Math.min(100, Math.max(0, parseFloat(predictionData.rf_model_probability)));
  const knnConf = Math.min(100, Math.max(0, parseFloat(predictionData.knn_model_probability)));
  const xgbLabel = predictionData.xgb_model_prediction;
  const rfLabel = predictionData.rf_model_prediction;
  const knnLabel = predictionData.knn_model_prediction;

  const modelResults = [
    { model: "XGBoost", label: xgbLabel, conf: xgbConf, delay: "0ms" },
    { model: "Random Forest", label: rfLabel, conf: rfConf, delay: "70ms" },
    { model: "KNN", label: knnLabel, conf: knnConf, delay: "140ms" },
  ];

  const finalLabel =
    predictionData.final_prediction || weightedVote(xgbLabel, rfLabel, knnLabel, xgbConf, rfConf, knnConf);
  const predictedCrop = cropData[finalLabel];

  const finalModel =
    modelResults.filter((m) => m.label === finalLabel).sort((a, b) => b.conf - a.conf)[0] || {
      model: "Model",
      conf: 0,
    };

  const finalConf = finalModel.conf;
  const modelUsed = finalModel.model;
  const agreeingModels = [
    xgbLabel === finalLabel && "XGBoost",
    rfLabel === finalLabel && "Random Forest",
    knnLabel === finalLabel && "KNN",
  ].filter(Boolean);

  const bestAlt = modelResults.filter((m) => m.label !== finalLabel).sort((a, b) => b.conf - a.conf)[0];
  const topSuggestions = getTopCropSuggestions(modelResults);
  const reasonHighlights = normalizeLocalizedCopy(getCropReasonHighlights(formData, finalLabel, language));

  const confClass = finalConf >= 80 ? "high" : finalConf >= 60 ? "mid" : "low";
  const suitability = normalizeLocalizedCopy(getSuitabilityMeta(finalConf, language));
  const explanationCards = normalizeLocalizedCopy([
    getConfidenceExplanation(finalConf, language),
    getConsensusExplanation(agreeingModels.length, modelResults.length, language),
    getDecisionEdgeExplanation(finalConf, bestAlt, language),
  ]);
  const localizedSeasons = normalizeLocalizedCopy(getLocalizedSeasons(language));
  const selectedSeason = localizedSeasons.find((item) => item.value === formData.season);

  const handleShare = () =>
    shareResult(
      `Grow ${predictedCrop?.title}`,
      `Crop Recommendation: ${predictedCrop?.title}\nConfidence: ${finalConf.toFixed(
        2
      )}% (${modelUsed})\nSupported by: ${agreeingModels.join(", ")}\n\nGenerated by Crop Recommender AI`
    );

  const handleDownload = () => {
    const lines = [
      "Crop Recommendation Report",
      "==========================",
      `Recommended Crop: ${predictedCrop?.title || finalLabel}`,
      `Confidence: ${finalConf.toFixed(2)}%`,
      `Model Used: ${modelUsed}`,
      `Supported By: ${agreeingModels.join(", ") || "No consensus"}`,
      "",
      "Input Summary",
      "-------------",
      `Nitrogen: ${formData.N || "--"}`,
      `Phosphorous: ${formData.P || "--"}`,
      `Potassium: ${formData.K || "--"}`,
      `Temperature: ${formData.temperature || "--"} C`,
      `Humidity: ${formData.humidity || "--"}%`,
      `Soil pH: ${formData.ph || "--"}`,
      `Rainfall: ${formData.rainfall || "--"} mm`,
      `Region: ${formData.region || "--"}`,
      `Season: ${formData.season || "--"}`,
      "",
      "Notes",
      "-----",
      predictedCrop?.description || "No description available.",
    ];

    downloadTextReport(
      `${String(finalLabel || "crop").toLowerCase().replace(/\s+/g, "-")}-recommendation.txt`,
      lines.join("\n")
    );
  };

  const handleOpenFertilizer = () => {
    history.push("/fertilizer", {
      prefillForm: {
        Nitrogen: formData.N || "",
        Potassium: formData.K || "",
        Phosphorous: formData.P || "",
        Temperature: formData.temperature || "",
        Humidity: formData.humidity || "",
        Moisture: "",
        soil_type: "",
        crop_type: mapCropToFertilizerType(finalLabel, predictedCrop?.title),
      },
      sourceCrop: predictedCrop?.title || finalLabel,
      sourceContext: {
        confidence: finalConf,
        model: modelUsed,
        region: formData.region || "",
        season: formData.season || "",
      },
    });
  };

  return (
    <div className="cr-result">
      <div className="cr-result__hero" style={imgError ? { background: "linear-gradient(135deg,#1a2512,#0a120a)" } : undefined}>
        {!imgError && (
          <img
            src={predictedCrop?.imageUrl}
            alt={predictedCrop?.title}
            className="cr-result__hero-img"
            onError={() => setImgError(true)}
          />
        )}
        <div className="cr-result__hero-overlay" />
        <div className="cr-result__hero-text">
          <div className="cr-result__eyebrow">{ui.mlRecommendedCrop}</div>
          <h1 className="cr-result__crop-name">{predictedCrop?.title}</h1>
          <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", flexWrap: "wrap" }}>
            <div className={`cr-conf-pill cr-conf-pill--${confClass}`}>
              {finalConf.toFixed(2)}% {ui.confidence} · {modelUsed}
            </div>
            <button className="cr-share-btn" onClick={handleShare} aria-label={ui.share}>
              {ui.share} ↗
            </button>
          </div>
        </div>
      </div>

      <div className="cr-result__body">
        <div className={`cr-suitability-banner cr-suitability-banner--${suitability.tone}`}>
          <strong>{suitability.label}</strong>
          <span>{suitability.note}</span>
        </div>
        <div className="cr-explain-grid">
          {explanationCards.map((card) => (
            <div key={`${card.title}-${card.detail}`} className="cr-explain-card">
              <div className="cr-explain-card__label">{card.title}</div>
              <div className="cr-explain-card__text">{card.detail}</div>
            </div>
          ))}
        </div>
        {agreeingModels.length > 0 && (
          <div className="cr-agree-row">
            <span className="cr-agree-row__icon" aria-hidden="true">
              ✓
            </span>
            <span>
              {ui.supportedByPrefix} <strong>{agreeingModels.join(", ")}</strong>
            </span>
          </div>
        )}
        {finalConf < 60 && (
          <div className="cr-warning" role="alert">
            ⚠ {ui.lowConfidence}
          </div>
        )}
        {bestAlt && (
          <div className="cr-alt-row">
            <span className="cr-alt-row__label">{ui.alternative}</span>
            <button className="cr-alt-row__crop" onClick={() => setSelectedCrop(bestAlt.label)}>
              {bestAlt.label}
            </button>
            <span className="cr-alt-row__meta">
              {bestAlt.conf.toFixed(2)}% via {bestAlt.model}
            </span>
          </div>
        )}

        <p className="cr-result__desc">{predictedCrop?.description || ui.noDescription}</p>

        {topSuggestions.length > 0 && (
          <>
            <div className="cr-section-label">{ui.topSuggestions}</div>
            <div className="cr-top-suggestions">
              {topSuggestions.map((item, index) => (
                <button
                  key={`${item.label}-${index}`}
                  type="button"
                  className={`cr-top-suggestion${item.label === finalLabel ? " cr-top-suggestion--active" : ""}`}
                  onClick={() => setSelectedCrop(item.label)}
                >
                  <span className="cr-top-suggestion__rank">#{index + 1}</span>
                  <span className="cr-top-suggestion__body">
                    <span className="cr-top-suggestion__name">{cropData[item.label]?.title || item.label}</span>
                    <span className="cr-top-suggestion__meta">
                      {item.confidence.toFixed(2)}% via {item.models.join(", ")}
                    </span>
                  </span>
                </button>
              ))}
            </div>
          </>
        )}

        {reasonHighlights.length > 0 && (
          <>
            <div className="cr-section-label">{ui.whyThisCrop}</div>
            <div className="cr-why-box">
              {reasonHighlights.map((reason, index) => (
                <div key={index} className="cr-why-box__item">
                  <span className="cr-why-box__dot" aria-hidden="true" />
                  <span>{reason}</span>
                </div>
              ))}
            </div>
          </>
        )}

        {(formData.region || formData.season) && (
          <>
            <div className="cr-section-label">{ui.regionSeasonContext}</div>
            <div className="cr-context-box">
              {formData.region && (
                <div className="cr-context-box__item">
                  <span className="cr-context-box__label">{ui.region}</span>
                  <span className="cr-context-box__value">{formData.region}</span>
                </div>
              )}
              {formData.season && (
                <div className="cr-context-box__item">
                  <span className="cr-context-box__label">{ui.season}</span>
                  <span className="cr-context-box__value">
                    {selectedSeason?.label || formData.season}
                    {getSeasonWindowLabel(formData.season, language)
                      ? ` | ${getSeasonWindowLabel(formData.season, language)}`
                      : ""}
                  </span>
                </div>
              )}
            </div>
          </>
        )}

        <CropCalendar cropKey={finalLabel} />

        <div className="cr-analysis-row">
          <RadarChart formData={formData} cropKey={finalLabel} />
          <VoteTriangle
            xgbLabel={xgbLabel}
            rfLabel={rfLabel}
            knnLabel={knnLabel}
            xgbConf={xgbConf}
            rfConf={rfConf}
            knnConf={knnConf}
            winner={finalLabel}
          />
        </div>

        <div className="cr-section-label">{ui.modelBreakdown}</div>
        <div className="cr-models-grid">
          {modelResults.map((m) => (
            <div
              key={m.model}
              className={`cr-model-badge${m.label === finalLabel ? " cr-model-badge--final" : ""}`}
              style={{ animationDelay: m.delay }}
            >
              <div className="cr-model-badge__header">
                <span className="cr-model-badge__name">{m.model}</span>
                {m.label === finalLabel && <span className="cr-model-badge__crown">★ {ui.winner}</span>}
              </div>
              <button className="cr-model-badge__crop" onClick={() => setSelectedCrop(m.label)}>
                {m.label}
              </button>
              <ConfidenceBar value={m.conf} />
            </div>
          ))}
        </div>

        {selectedCrop && selectedCrop !== finalLabel && (
          <CropDetailPanel cropKey={selectedCrop} onClose={() => setSelectedCrop(null)} />
        )}

        <div className="cr-result__actions">
          <button className="cr-btn cr-btn--ghost" onClick={handleDownload}>
            {ui.downloadResult}
          </button>
          <button className="cr-btn cr-btn--ghost" onClick={handleOpenFertilizer}>
            {ui.goToFertilizer}
          </button>
          <button className="cr-btn cr-btn--ghost" onClick={onBack}>
            {ui.backToPrediction}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CropMlResultPanel;
